fix:
  initiator:
    reset-store-on-start: true
    sessions:
      - host: 127.0.0.1
        port: 9878
        begin-string: FIX.4.4
        sender-comp-id: INITIATOR1
        target-comp-id: ACCEPTOR
      - host: 127.0.0.1
        port: 9878
        begin-string: FIX.4.4
        sender-comp-id: INITIATOR2
        target-comp-id: ACCEPTOR
